var client = require('../dbConnection').getInstance().getClient();
var Labor = require('../models/Labor');

client.sync().then(function() {
  
	var labores = [
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"Alta",
    "nivel":4154,
    "fase":"Preparación",
    "Tipo labor":"Rpa.",
    "Labor":"403 W",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Rpa acceso St335",
    "Prioridad":1,
    "Suma - avance.programado":42,
    "id":"Rpa. 403 W",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":4154,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"350 W",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Preparacion St 335",
    "Prioridad":1,
    "Suma - avance.programado":15,
    "id":"Rpa. 350 W",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":4050,
    "fase":"Preparación",
    "Tipo labor":"Cro.",
    "Labor":"387 N",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Rpa acceso St369 Sup",
    "Prioridad":1,
    "Suma - avance.programado":40,
    "id":"Cro. 387 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":4050,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"404 E",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Camara Carguio Rp369",
    "Prioridad":1,
    "Suma - avance.programado":15,
    "id":"Cro. 404 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":4050,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"389 N",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Rpa minado St369-v lind",
    "Prioridad":2,
    "Suma - avance.programado":35,
    "id":"Cro. 389 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"SB baja",
    "nivel":3420,
    "fase":"Preparación",
    "Tipo labor":"Cro.",
    "Labor":"727 W",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Ventilación",
    "Prioridad":1,
    "Suma - avance.programado":35.5,
    "id":"Cro. 727 W",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":3420,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"838 W",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Cámara diamantina",
    "Prioridad":2,
    "Suma - avance.programado":8,
    "id":"Cro. 838 W",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":3420,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"7854 E",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Rpa. minado OB 18 stp. 660",
    "Prioridad":null,
    "Suma - avance.programado":30,
    "id":"Rpa. 7854 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"",
    "nivel":3420,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"7840 N",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Acceso a Stp. 660 N",
    "Prioridad":1,
    "Suma - avance.programado":10.5,
    "id":"Rpa. 7840 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"COPSEM",
    "Zona":"Ata intermedio",
    "nivel":3600,
    "fase":"Preparación",
    "Tipo labor":"Rpa.",
    "Labor":"782 N",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Rpa. minado stp. 154",
    "Prioridad":1,
    "Suma - avance.programado":30,
    "id":"Rpa. 782 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"Ata baja",
    "nivel":3300,
    "fase":"Exploración",
    "Tipo labor":"Cro.",
    "Labor":"634 E",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Exploración",
    "Prioridad":2,
    "Suma - avance.programado":25,
    "id":"Cro. 634 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"Preparación",
    "Tipo labor":"Cro.",
    "Labor":"544 E",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Preparación de nivel 3300",
    "Prioridad":1,
    "Suma - avance.programado":40,
    "id":"Cro. 544 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"624 E",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Apertura de mineralización",
    "Prioridad":2,
    "Suma - avance.programado":15,
    "id":"Cro. 624 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"456 S",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Ampliación de sección",
    "Prioridad":1,
    "Suma - avance.programado":120,
    "id":"Cro. 456 S",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"642 E",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Pie de RB de ventilación",
    "Prioridad":1,
    "Suma - avance.programado":50,
    "id":"Cro. 642 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"734 N",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Apertura de Nivel",
    "Prioridad":1,
    "Suma - avance.programado":25,
    "id":"Cro. 734 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Cro.",
    "Labor":"939 W",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Camara diamantina",
    "Prioridad":1,
    "Suma - avance.programado":20,
    "id":"Cro. 939 W",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Gal.",
    "Labor":"611 N",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Apertura de mineralización",
    "Prioridad":1,
    "Suma - avance.programado":25,
    "id":"Gal. 611 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Gal.",
    "Labor":"602 W",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Apertura de mineralización",
    "Prioridad":1,
    "Suma - avance.programado":10,
    "id":"Gal. 602 W",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"910 S",
    "ancho_pro":5,
    "alto_pro":5,
    "nombre":"Rpa. Principal",
    "Prioridad":1,
    "Suma - avance.programado":60,
    "id":"Rpa. 910 S",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"857 N",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Acceso a Rpa. 910 S",
    "Prioridad":1,
    "Suma - avance.programado":40,
    "id":"Rpa. 857 N",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"992 E",
    "ancho_pro":4.5,
    "alto_pro":4,
    "nombre":"Acceso a Nv. 3360-Ventilación",
    "Prioridad":1,
    "Suma - avance.programado":60,
    "id":"Rpa. 992 E",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"801 S",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Acceso a Stp. 765 N",
    "Prioridad":2,
    "Suma - avance.programado":15,
    "id":"Rpa. 801 S",
    "FIELD13":" ",
    "tipoTipoId":"A"
  },
  {
    "empresaEmpresaid":"MAPERU",
    "Zona":"",
    "nivel":3300,
    "fase":"",
    "Tipo labor":"Rpa.",
    "Labor":"815 S",
    "ancho_pro":4,
    "alto_pro":4,
    "nombre":"Acceso a Stp. 765 N",
    "Prioridad":2,
    "Suma - avance.programado":20,
    "id":"Rpa. 815 S",
    "FIELD13":" ",
    "tipoTipoId":"A"
  }
]

    ;

  labores.forEach(function(item) {
    Labor.create({
      codigo: item.id,
     	nombre: item.nombre,       
      nivel: item.nivel, 
      ancho_pro:item.ancho_pro,
      alto_pro:item.alto_pro,
      tipoTipoId:item.tipoTipoId,
      empresaEmpresaid:item.empresaEmpresaid,
    })
    .then(function(tipo) {
      console.log('tipo ' + item.nombre + ' creado');
    })
    .catch(function(err) {
      console.log(err);
    })
  })
})
.catch(function(err) {
  console.log(err);
});

